In [ ]:
print("Anshu")

Anshu

Pandas

In [2]:
!npm install pandas

up to date, audited 2 packages in 1s

found 0 vulnerabilities

In [3]:
import pandas as pd

In [2]:
s=pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])

In [3]:
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
df=pd.DataFrame({"Name":['Anshu','Anshul','Anshika','Anshuman'],'Age':[20,21,22,23],'City':['Delhi','Mumbai','Kolkata','Chennai']})

In [ ]:
df

       Name  Age     City
0     Anshu   20    Delhi
1    Anshul   21   Mumbai
2   Anshika   22  Kolkata
3  Anshuman   23  Chennai

Read Data File

In [6]:
df=pd.read_csv("data/data.csv")

In [4]:
print("Pandas version:", pd.__version__)

Pandas version: 3.0.6

In [7]:
df

,Series_reference,Period,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3
0,CPIM.SE901,1960.01,45.923461,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
1,CPIM.SE901,1960.02,45.498637,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
2,CPIM.SE901,1960.03,45.116296,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
3,CPIM.SE901,1960.04,45.158779,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
4,CPIM.SE901,1960.05,45.286226,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
60210,CPIM.SE904502,2026.05,1680.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60211,CPIM.SE904502,2026.06,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60212,CPIM.SE904502,2026.07,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60213,CPIM.SE904502,2026.08,1702.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60214,CPIM.SE904502,2026.09,1732.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN

In [8]:
df.head()

,Series_reference,Period,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3
0,CPIM.SE901,1960.01,45.923461,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
1,CPIM.SE901,1960.02,45.498637,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
2,CPIM.SE901,1960.03,45.116296,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
3,CPIM.SE901,1960.04,45.158779,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
4,CPIM.SE901,1960.05,45.286226,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN

In [9]:
df.tail()

,Series_reference,Period,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3
60210,CPIM.SE904502,2026.05,1680.0,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60211,CPIM.SE904502,2026.06,1695.0,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60212,CPIM.SE904502,2026.07,1695.0,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60213,CPIM.SE904502,2026.08,1702.0,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60214,CPIM.SE904502,2026.09,1732.0,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN

In [10]:
df.describe()

             Period    Data_value
count  60215.000000  60124.000000
mean    2014.177396    385.547651
std        9.715534    511.381061
min     1960.010000     -2.000000
25%     2010.050000      3.440000
50%     2016.020000      8.890000
75%     2021.060000    908.292386
max     2026.090000   3222.000000

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60215 entries, 0 to 60214
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Series_reference  60215 non-null  str
 1   Period            60215 non-null  float64
 2   Data_value        60124 non-null  float64
 3   STATUS            60215 non-null  str
 4   UNITS             60215 non-null  str
 5   Subject           60215 non-null  str
 6   Group             60215 non-null  str
 7   Series_title_1    60215 non-null  str
 8   Series_title_2    1672 non-null   str
 9   Series_title_3    1672 non-null   str
dtypes: float64(2), str(8)
memory usage: 4.6 MB

Data Selection

In [14]:
df["Period"]

0        1960.01
1        1960.02
2        1960.03
3        1960.04
4        1960.05
          ...
60210    2026.05
60211    2026.06
60212    2026.07
60213    2026.08
60214    2026.09
Name: Period, Length: 60215, dtype: float64

In [15]:
type(df["Period"])

pandas.Series

In [16]:
df[["Period","Data_value"]]

        Period   Data_value
0      1960.01    45.923461
1      1960.02    45.498637
2      1960.03    45.116296
3      1960.04    45.158779
4      1960.05    45.286226
...        ...          ...
60210  2026.05  1680.000000
60211  2026.06  1695.000000
60212  2026.07  1695.000000
60213  2026.08  1702.000000
60214  2026.09  1732.000000

[60215 rows x 2 columns]

In [17]:
df.iloc[0]

Series_reference                                           CPIM.SE901
Period                                                        1960.01
Data_value                                                  45.923461
STATUS                                                          FINAL
UNITS                                                           Index
Subject                                   Consumers Price Index - CPI
Group               Food Price Index Level 1 Groups for New Zealan...
Series_title_1                                                   Food
Series_title_2                                                    NaN
Series_title_3                                                    NaN
Name: 0, dtype: object

In [18]:
type(df.iloc[0])

pandas.Series

In [20]:
df2=pd.read_csv("data/data - Copy.csv")

In [22]:
df2.head()

,Series_reference,Period,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3
0,CPIM.SE901,NaN,45.923461,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
1,CPIM.SE901,1960.02,45.498637,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
2,CPIM.SE901,1960.03,45.116296,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
3,CPIM.SE901,1960.04,45.158779,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
4,CPIM.SE901,1960.05,45.286226,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN

In [23]:
df2.dropna()

,Series_reference,Period,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3
55911,CPIM.SE1041F,2006.11,1000.0,FINAL,Index,Consumers Price Index - CPI,CPI Monthly Rents (Broad Regions),Auckland,Actual rentals for housing,Flow
55912,CPIM.SE1041F,2006.12,995.0,FINAL,Index,Consumers Price Index - CPI,CPI Monthly Rents (Broad Regions),Auckland,Actual rentals for housing,Flow
55913,CPIM.SE1041F,2007.01,1007.0,FINAL,Index,Consumers Price Index - CPI,CPI Monthly Rents (Broad Regions),Auckland,Actual rentals for housing,Flow
55914,CPIM.SE1041F,2007.02,1012.0,FINAL,Index,Consumers Price Index - CPI,CPI Monthly Rents (Broad Regions),Auckland,Actual rentals for housing,Flow
55915,CPIM.SE1041F,2007.03,1020.0,FINAL,Index,Consumers Price Index - CPI,CPI Monthly Rents (Broad Regions),Auckland,Actual rentals for housing,Flow
...,...,...,...,...,...,...,...,...,...,...
57578,CPIM.SE9041S,2026.05,1810.0,FINAL,Index,Consumers Price Index - CPI,CPI Monthly Rents (National),National,Actual rentals for housing,Stock
57579,CPIM.SE9041S,2026.06,1811.0,FINAL,Index,Consumers Price Index - CPI,CPI Monthly Rents (National),National,Actual rentals for housing,Stock
57580,CPIM.SE9041S,2026.07,1810.0,FINAL,Index,Consumers Price Index - CPI,CPI Monthly Rents (National),National,Actual rentals for housing,Stock
57581,CPIM.SE9041S,2026.08,1810.0,FINAL,Index,Consumers Price Index - CPI,CPI Monthly Rents (National),National,Actual rentals for housing,Stock
57582,CPIM.SE9041S,2026.09,1811.0,FINAL,Index,Consumers Price Index - CPI,CPI Monthly Rents (National),National,Actual rentals for housing,Stock

In [24]:
df2.fillna(0)

,Series_reference,Period,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3
0,CPIM.SE901,0.00,45.923461,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,0,0
1,CPIM.SE901,1960.02,45.498637,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,0,0
2,CPIM.SE901,1960.03,45.116296,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,0,0
3,CPIM.SE901,1960.04,45.158779,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,0,0
4,CPIM.SE901,1960.05,45.286226,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,0,0
...,...,...,...,...,...,...,...,...,...,...
60210,CPIM.SE904502,2026.05,1680.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,0,0
60211,CPIM.SE904502,2026.06,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,0,0
60212,CPIM.SE904502,2026.07,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,0,0
60213,CPIM.SE904502,2026.08,1702.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,0,0
60214,CPIM.SE904502,2026.09,0.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,0,0

In [25]:
df

,Series_reference,Period,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3
0,CPIM.SE901,1960.01,45.923461,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
1,CPIM.SE901,1960.02,45.498637,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
2,CPIM.SE901,1960.03,45.116296,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
3,CPIM.SE901,1960.04,45.158779,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
4,CPIM.SE901,1960.05,45.286226,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
60210,CPIM.SE904502,2026.05,1680.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60211,CPIM.SE904502,2026.06,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60212,CPIM.SE904502,2026.07,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60213,CPIM.SE904502,2026.08,1702.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60214,CPIM.SE904502,2026.09,1732.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN

In [26]:
df.rename(columns={"Period":"Year"})

,Series_reference,Year,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3
0,CPIM.SE901,1960.01,45.923461,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
1,CPIM.SE901,1960.02,45.498637,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
2,CPIM.SE901,1960.03,45.116296,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
3,CPIM.SE901,1960.04,45.158779,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
4,CPIM.SE901,1960.05,45.286226,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
60210,CPIM.SE904502,2026.05,1680.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60211,CPIM.SE904502,2026.06,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60212,CPIM.SE904502,2026.07,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60213,CPIM.SE904502,2026.08,1702.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60214,CPIM.SE904502,2026.09,1732.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN

In [27]:
df

,Series_reference,Period,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3
0,CPIM.SE901,1960.01,45.923461,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
1,CPIM.SE901,1960.02,45.498637,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
2,CPIM.SE901,1960.03,45.116296,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
3,CPIM.SE901,1960.04,45.158779,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
4,CPIM.SE901,1960.05,45.286226,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
60210,CPIM.SE904502,2026.05,1680.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60211,CPIM.SE904502,2026.06,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60212,CPIM.SE904502,2026.07,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60213,CPIM.SE904502,2026.08,1702.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60214,CPIM.SE904502,2026.09,1732.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN

In [ ]:
#rename the column "Period" to "Year" in the DataFrame df and make the change permanent by using inplace=True
df.rename(columns={"Period":"Year"},inplace=True)

In [29]:
df

,Series_reference,Year,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3
0,CPIM.SE901,1960.01,45.923461,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
1,CPIM.SE901,1960.02,45.498637,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
2,CPIM.SE901,1960.03,45.116296,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
3,CPIM.SE901,1960.04,45.158779,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
4,CPIM.SE901,1960.05,45.286226,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
60210,CPIM.SE904502,2026.05,1680.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60211,CPIM.SE904502,2026.06,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60212,CPIM.SE904502,2026.07,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60213,CPIM.SE904502,2026.08,1702.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60214,CPIM.SE904502,2026.09,1732.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN

In [31]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60215 entries, 0 to 60214
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Series_reference  60215 non-null  str
 1   Year              60215 non-null  float64
 2   Data_value        60124 non-null  float64
 3   STATUS            60215 non-null  str
 4   UNITS             60215 non-null  str
 5   Subject           60215 non-null  str
 6   Group             60215 non-null  str
 7   Series_title_1    60215 non-null  str
 8   Series_title_2    1672 non-null   str
 9   Series_title_3    1672 non-null   str
dtypes: float64(2), str(8)
memory usage: 4.6 MB

Chenge Data Type

In [32]:
df['Year']=df['Year'].astype('str')

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60215 entries, 0 to 60214
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Series_reference  60215 non-null  str
 1   Year              60215 non-null  str
 2   Data_value        60124 non-null  float64
 3   STATUS            60215 non-null  str
 4   UNITS             60215 non-null  str
 5   Subject           60215 non-null  str
 6   Group             60215 non-null  str
 7   Series_title_1    60215 non-null  str
 8   Series_title_2    1672 non-null   str
 9   Series_title_3    1672 non-null   str
dtypes: float64(1), str(9)
memory usage: 4.6 MB

In [34]:
df

,Series_reference,Year,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3
0,CPIM.SE901,1960.01,45.923461,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
1,CPIM.SE901,1960.02,45.498637,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
2,CPIM.SE901,1960.03,45.116296,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
3,CPIM.SE901,1960.04,45.158779,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
4,CPIM.SE901,1960.05,45.286226,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
60210,CPIM.SE904502,2026.05,1680.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60211,CPIM.SE904502,2026.06,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60212,CPIM.SE904502,2026.07,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60213,CPIM.SE904502,2026.08,1702.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN
60214,CPIM.SE904502,2026.09,1732.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN

In [35]:
df['Year'][0]

'1960.01'

No of rows

In [38]:
len(df)

60215

In [39]:
df["zeros"]=[0 for i in range(len(df))]

In [40]:
df

,Series_reference,Year,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3,zeros
0,CPIM.SE901,1960.01,45.923461,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0
1,CPIM.SE901,1960.02,45.498637,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0
2,CPIM.SE901,1960.03,45.116296,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0
3,CPIM.SE901,1960.04,45.158779,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0
4,CPIM.SE901,1960.05,45.286226,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...
60210,CPIM.SE904502,2026.05,1680.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN,0
60211,CPIM.SE904502,2026.06,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN,0
60212,CPIM.SE904502,2026.07,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN,0
60213,CPIM.SE904502,2026.08,1702.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN,0
60214,CPIM.SE904502,2026.09,1732.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN,0

In [41]:
def fx(a):
    return a+2
df["Zeros + 2"]=df["zeros"].apply(fx)

In [42]:
df

,Series_reference,Year,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3,zeros,Zeros + 2
0,CPIM.SE901,1960.01,45.923461,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0,2
1,CPIM.SE901,1960.02,45.498637,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0,2
2,CPIM.SE901,1960.03,45.116296,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0,2
3,CPIM.SE901,1960.04,45.158779,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0,2
4,CPIM.SE901,1960.05,45.286226,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
60210,CPIM.SE904502,2026.05,1680.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN,0,2
60211,CPIM.SE904502,2026.06,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN,0,2
60212,CPIM.SE904502,2026.07,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN,0,2
60213,CPIM.SE904502,2026.08,1702.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN,0,2
60214,CPIM.SE904502,2026.09,1732.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN,0,2

Data save a new file

In [44]:
df.to_csv("data/export.csv ",index=False)

Merging

In [45]:
df1=pd.DataFrame({"Name":['Anshu','Anshul','Anshika','Anshuman'],
                  'Age':[20,21,22,23],
                  'City':['Delhi','Mumbai','Kolkata','Chennai']
                  })

In [46]:
df1

       Name  Age     City
0     Anshu   20    Delhi
1    Anshul   21   Mumbai
2   Anshika   22  Kolkata
3  Anshuman   23  Chennai

In [47]:
df2=pd.DataFrame({"Name":['Tirth','lusi','Teju','Neel'],'Age':[20,21,22,23],'City':['Delhi','Mumbai','Odisha','Chennai']})

In [48]:
df2

    Name  Age     City
0  Tirth   20    Delhi
1   lusi   21   Mumbai
2   Teju   22   Odisha
3   Neel   23  Chennai

Concatinate

In [49]:
pd.concat([df1,df2])

       Name  Age     City
0     Anshu   20    Delhi
1    Anshul   21   Mumbai
2   Anshika   22  Kolkata
3  Anshuman   23  Chennai
0     Tirth   20    Delhi
1      lusi   21   Mumbai
2      Teju   22   Odisha
3      Neel   23  Chennai

In [50]:
df1=pd.DataFrame({"Name":['Anshu','Anshul'],'Age':[20,21],'City':['Delhi','Mumbai']})

In [51]:
df1

     Name  Age    City
0   Anshu   20   Delhi
1  Anshul   21  Mumbai

In [52]:
df2=pd.DataFrame({"Name":['Anshu','Anshul'],'mark':[20,21]})

In [53]:
df2

     Name  mark
0   Anshu    20
1  Anshul    21

In [54]:
pd.merge(df1,df2,on="Name")

     Name  Age    City  mark
0   Anshu   20   Delhi    20
1  Anshul   21  Mumbai    21

In [57]:
df.shape

(60215, 12)

In [58]:
df.index

RangeIndex(start=0, stop=60215, step=1)

In [59]:
df.columns

Index(['Series_reference', 'Year', 'Data_value', 'STATUS', 'UNITS', 'Subject',
       'Group', 'Series_title_1', 'Series_title_2', 'Series_title_3', 'zeros',
       'Zeros + 2'],
      dtype='str')

In [60]:
df.dtypes

Series_reference        str
Year                    str
Data_value          float64
STATUS                  str
UNITS                   str
Subject                 str
Group                   str
Series_title_1          str
Series_title_2          str
Series_title_3          str
zeros                 int64
Zeros + 2             int64
dtype: object

In [ ]:
#random sampling of rows from a DataFrame
df.sample()

,Series_reference,Year,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3,zeros,Zeros + 2
1699,CPIM.SE901102,2019.08,904.0,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 3 Classes for New Zealand,Vegetables,NaN,NaN,0,2

In [ ]:
#unique values in each column of a DataFrame
df.nunique()

Series_reference      237
Year                  801
Data_value          12821
STATUS                  2
UNITS                   3
Subject                 1
Group                  15
Series_title_1        214
Series_title_2          1
Series_title_3          2
zeros                   1
Zeros + 2               1
dtype: int64

In [ ]:
#frequency of unique values in each column of a DataFrame
df.value_counts()

Series_reference  Year     Data_value  STATUS  UNITS  Subject                      Group                              Series_title_1  Series_title_2              Series_title_3  zeros  Zeros + 2
CPIM.SE1041F      2006.11  1000.0      FINAL   Index  Consumers Price Index - CPI  CPI Monthly Rents (Broad Regions)  Auckland        Actual rentals for housing  Flow            0      2            1
                  2006.12  995.0       FINAL   Index  Consumers Price Index - CPI  CPI Monthly Rents (Broad Regions)  Auckland        Actual rentals for housing  Flow            0      2            1
                  2007.01  1007.0      FINAL   Index  Consumers Price Index - CPI  CPI Monthly Rents (Broad Regions)  Auckland        Actual rentals for housing  Flow            0      2            1
                  2007.02  1012.0      FINAL   Index  Consumers Price Index - CPI  CPI Monthly Rents (Broad Regions)  Auckland        Actual rentals for housing  Flow            0      2            1
                  2007.03  1020.0      FINAL   Index  Consumers Price Index - CPI  CPI Monthly Rents (Broad Regions)  Auckland        Actual rentals for housing  Flow            0      2            1
                                                                                                                                                                                                     ..
CPIM.SE9041S      2026.05  1810.0      FINAL   Index  Consumers Price Index - CPI  CPI Monthly Rents (National)       National        Actual rentals for housing  Stock           0      2            1
                  2026.06  1811.0      FINAL   Index  Consumers Price Index - CPI  CPI Monthly Rents (National)       National        Actual rentals for housing  Stock           0      2            1
                  2026.07  1810.0      FINAL   Index  Consumers Price Index - CPI  CPI Monthly Rents (National)       National        Actual rentals for housing  Stock           0      2            1
                  2026.08  1810.0      FINAL   Index  Consumers Price Index - CPI  CPI Monthly Rents (National)       National        Actual rentals for housing  Stock           0      2            1
                  2026.09  1811.0      FINAL   Index  Consumers Price Index - CPI  CPI Monthly Rents (National)       National        Actual rentals for housing  Stock           0      2            1
Name: count, Length: 1672, dtype: int64

In [64]:
df.loc[0]

Series_reference                                           CPIM.SE901
Year                                                          1960.01
Data_value                                                  45.923461
STATUS                                                          FINAL
UNITS                                                           Index
Subject                                   Consumers Price Index - CPI
Group               Food Price Index Level 1 Groups for New Zealan...
Series_title_1                                                   Food
Series_title_2                                                    NaN
Series_title_3                                                    NaN
zeros                                                               0
Zeros + 2                                                           2
Name: 0, dtype: object

In [65]:
df.iloc[0]

Series_reference                                           CPIM.SE901
Year                                                          1960.01
Data_value                                                  45.923461
STATUS                                                          FINAL
UNITS                                                           Index
Subject                                   Consumers Price Index - CPI
Group               Food Price Index Level 1 Groups for New Zealan...
Series_title_1                                                   Food
Series_title_2                                                    NaN
Series_title_3                                                    NaN
zeros                                                               0
Zeros + 2                                                           2
Name: 0, dtype: object

In [67]:
df["Year"]

0        1960.01
1        1960.02
2        1960.03
3        1960.04
4        1960.05
          ...
60210    2026.05
60211    2026.06
60212    2026.07
60213    2026.08
60214    2026.09
Name: Year, Length: 60215, dtype: str

In [70]:
df['Year']=df['Year'].astype('float64')

In [73]:
df[df["Year"] > 2000]

,Series_reference,Year,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3,zeros,Zeros + 2
480,CPIM.SE901,2000.01,655.568537,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0,2
481,CPIM.SE901,2000.02,648.491742,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0,2
482,CPIM.SE901,2000.03,649.135087,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0,2
483,CPIM.SE901,2000.04,645.918362,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0,2
484,CPIM.SE901,2000.05,646.561707,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
60210,CPIM.SE904502,2026.05,1680.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN,0,2
60211,CPIM.SE904502,2026.06,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN,0,2
60212,CPIM.SE904502,2026.07,1695.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN,0,2
60213,CPIM.SE904502,2026.08,1702.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN,0,2
60214,CPIM.SE904502,2026.09,1732.000000,FINAL,Index,Consumers Price Index - CPI,CPI Level 3 Classes for New Zealand,Gas,NaN,NaN,0,2

In [72]:
df[(df["Year"] > 2000)&(df["Year"] < 2010)]

,Series_reference,Year,Data_value,STATUS,UNITS,Subject,Group,Series_title_1,Series_title_2,Series_title_3,zeros,Zeros + 2
480,CPIM.SE901,2000.01,655.568537,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0,2
481,CPIM.SE901,2000.02,648.491742,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0,2
482,CPIM.SE901,2000.03,649.135087,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0,2
483,CPIM.SE901,2000.04,645.918362,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0,2
484,CPIM.SE901,2000.05,646.561707,FINAL,Index,Consumers Price Index - CPI,Food Price Index Level 1 Groups for New Zealan...,Food,NaN,NaN,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...
57377,CPIM.SE9041S,2009.08,1102.000000,FINAL,Index,Consumers Price Index - CPI,CPI Monthly Rents (National),National,Actual rentals for housing,Stock,0,2
57378,CPIM.SE9041S,2009.09,1103.000000,FINAL,Index,Consumers Price Index - CPI,CPI Monthly Rents (National),National,Actual rentals for housing,Stock,0,2
57379,CPIM.SE9041S,2009.10,1103.000000,FINAL,Index,Consumers Price Index - CPI,CPI Monthly Rents (National),National,Actual rentals for housing,Stock,0,2
57380,CPIM.SE9041S,2009.11,1104.000000,FINAL,Index,Consumers Price Index - CPI,CPI Monthly Rents (National),National,Actual rentals for housing,Stock,0,2
57381,CPIM.SE9041S,2009.12,1105.000000,FINAL,Index,Consumers Price Index - CPI,CPI Monthly Rents (National),National,Actual rentals for housing,Stock,0,2

In [75]:
df1[df1["Age"].isin([20])]

    Name  Age   City
0  Anshu   20  Delhi

In [86]:
df1[df1["Age"].between(15, 23)]

     Name  Age    City  age
1  Anshul   21  Mumbai  NaN

In [83]:

df1.loc[0,"Age"] = 25

In [85]:
df1

     Name  Age    City   age
0   Anshu   25   Delhi  25.0
1  Anshul   21  Mumbai   NaN

In [91]:
df1.drop(columns=["age"], inplace=True)

In [92]:
df1

     Name  Age    City
0   Anshu   25   Delhi
1  Anshul   21  Mumbai

In [94]:
df1.query("Age>=25")

    Name  Age   City
0  Anshu   25  Delhi

In [95]:
df1.sort_values(by="Age")

     Name  Age    City
1  Anshul   21  Mumbai
0   Anshu   25   Delhi

In [102]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    10 non-null     str
 1   age     10 non-null     float64
 2   city    10 non-null     str
dtypes: float64(1), str(2)
memory usage: 660.0 bytes

In [ ]:
#add new rows to the DataFrame df1
new_data = {
    'name': ['Rahul', 'Priya', 'Amit', 'Sneha', 'Vikas',
             'Neha', 'Rohit', 'Pooja', 'Arjun', 'Kavya'],
    'age': [22, 25, 28, 21, 30, 24, 27, 23, 26, 29],
    'city': ['Delhi', 'Mumbai', 'Pune', 'Delhi', 'Jaipur',
             'Mumbai', 'Hyderabad', 'Pune', 'Delhi', 'Jaipur']
}

df1=pd.concat([df1, pd.DataFrame(new_data)], ignore_index=True)

In [ ]:
#delete all rows from the DataFrame df1
df1.drop(df1.index, inplace=True)

In [109]:
df1

    name   age       city
0  Rahul  22.0      Delhi
1  Priya  25.0     Mumbai
2   Amit  28.0       Pune
3  Sneha  21.0      Delhi
4  Vikas  30.0     Jaipur
5   Neha  24.0     Mumbai
6  Rohit  27.0  Hyderabad
7  Pooja  23.0       Pune
8  Arjun  26.0      Delhi
9  Kavya  29.0     Jaipur

groupBy

In [119]:
df1.groupby("city").size()

city
Delhi        3
Hyderabad    1
Jaipur       2
Mumbai       2
Pune         2
dtype: int64

In [123]:
print(df1["age"].sum())
print(df1["age"].mean())
print(df1["age"].max())
print(df1["age"].min())
print(df1["age"].median())
print(df1["age"].std())
print(df1["age"].count())

255.0
25.5
30.0
21.0
25.5
3.0276503540974917
10